FROM vote-base AS builder
RUN --mount=type=cache,target=/root/.gradle \
    ./gradlew :adm:bootJar --no-daemon

FROM gcr.io/distroless/java21-debian12:nonroot

WORKDIR /app

COPY --from=builder /workspace/adm/build/libs/adm.jar app.jar

ENV JAVA_TOOL_OPTIONS=""

EXPOSE 8089

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
