FROM vote-base AS builder
RUN --mount=type=cache,target=/root/.gradle \
    ./gradlew :api:bootJar --no-daemon

FROM gcr.io/distroless/java21-debian12:nonroot

WORKDIR /app

COPY --from=builder /workspace/api/build/libs/api.jar app.jar

ENV JAVA_TOOL_OPTIONS=""

EXPOSE 8088

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
