@baseUrl = http://localhost:8088
@candidateId = 1

### 후보 목록 조회
GET {{baseUrl}}/api/v1/candidates
Accept: application/json

### 후보 단건 조회
GET {{baseUrl}}/api/v1/candidates/{{candidateId}}
Accept: application/json
