server:
  port: 8089

spring:
  docker.compose:
    file: docker-local/compose.yaml
    lifecycle-management: start-only
  datasource:
    url: jdbc:mysql://localhost:3306/vote
    username: root
    password: root
  r2dbc:
    url: r2dbc:mysql://localhost:3306/vote
    username: root
    password: root

#logging:
#  level:
