@baseUrl = http://localhost:8089
@policyId = 1

### 투표 정책 생성
POST {{baseUrl}}/api/v1/adm/policies
Content-Type: application/json

{
  "name": "기본 다수결",
  "type": "MAJORITY",
  "params": "{\"maxChoices\":1}"
}

### 투표 정책 수정
PATCH {{baseUrl}}/api/v1/adm/policies/{{policyId}}
Content-Type: application/json

{
  "name": "기본 다수결 수정",
  "type": "MAJORITY",
  "params": "{\"maxChoices\":1,\"allowAbstain\":false}"
}

### 투표 정책 삭제
DELETE {{baseUrl}}/api/v1/adm/policies/{{policyId}}
