@baseUrl = http://localhost:8089
@policyId = 1

### 투표 정책 생성
POST {{baseUrl}}/api/v1/adm/policies
Content-Type: application/json

{
  "name": "단일 선택 정책",
  "type": "SingleChoicePolicy",
  "params": "{}"
}

### 투표 정책 수정
PATCH {{baseUrl}}/api/v1/adm/policies/{{policyId}}
Content-Type: application/json

{
  "name": "복합 투표 정책",
  "type": "CompositePolicy",
  "params": "{\"policies\":[{\"type\":\"SingleChoicePolicy\",\"params\":{}},{\"type\":\"MultipleChoicePolicy\",\"params\":{\"minChoices\":1,\"maxChoices\":2}}]}"
}

### 투표 정책 삭제
DELETE {{baseUrl}}/api/v1/adm/policies/{{policyId}}
