server:
  port: 8088

spring:
  docker.compose:
    file: docker-local/compose.yaml
    lifecycle-management: start-only
  flyway:
    url: jdbc:mysql://localhost:3306/vote
    user: root
    password: root
  datasource:
    url: jdbc:mysql://localhost:3306/vote
    username: root
    password: root
  r2dbc:
    url: r2dbc:mysql://localhost:3306/vote
    username: root
    password: root

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

#logging:
#  level:
